### ISSUE TITLE
LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.

### ISSUE THREAD

**Issue by devinjdawson** [trdwll/SteamBridge#13]
```UnrealEngine/Engine/Plugins/SteamBridge-1.0.4-Release/Source/SteamBridge/Public/SteamStructs.h(49) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.```

I get many of these errors when trying to compile the plugin with the 4.26.2 Engine from source. Plugin version 1.0.4. Is this not supposed to be how it works? I've been installing plugins directly to work with them more easily across projects.

**Comment by trdwll** [comment]
It's fixed in the [develop](https://github.com/trdwll/SteamBridge/tree/develop) branch. I just haven't pushed develop to main or the marketplace yet.
