### ISSUE TITLE
Crashing with "Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000"

### ISSUE THREAD

**Issue by unclemusclez** [trdwll/SteamBridge#15]
I get `Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000` grabbing the steam id from launching the game within the viewport. If I launch the game outside of the editor, it seems to run fine. I assume this is because it is trying to grab the steam ID, and that is not standard functionality within the editor. 

```UE4Editor_SteamBridge!USteamUser::execGetSteamID() [G:\UnrealEngine\Engine\Plugins\SteamBridge-develop\Intermediate\Build\Win64\UE4Editor\Inc\SteamBridge\SteamUser.gen.cpp:595]
UE4Editor_CoreUObject!UFunction::Invoke() [G:\UnrealEngine\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:5588]```

4.26.2 and develop branch of plugin

**Comment by trdwll** [comment]
You have to run the game via right-click uproject.
