### ISSUE TITLE
Error: cast to 'const char *' from smaller integer type 'char'

### ISSUE THREAD

**Issue by highlyunavailable** [trdwll/SteamBridge#16]
SteamBridge\Public\Core\SteamRemotePlay.h(65,63): error: cast to 'const char *' from smaller integer type 'char' [-Werror,-Wint-to-pointer-cast]

`FString GetSessionClientName(int32 SessionID) const { return UTF8_TO_TCHAR(*SteamRemotePlay()->GetSessionClientName(SessionID)); }`

This should probably be
`FString GetSessionClientName(int32 SessionID) const { return UTF8_TO_TCHAR(SteamRemotePlay()->GetSessionClientName(SessionID)); }`

instead (remove the dereference of the result of GetSessionClientName) because `UTF8_TO_TCHAR` casts the input as a pointer.

**Comment by trdwll** [comment]
This has already been solved in the develop branch.
