### ISSUE TITLE
UE 4.27.2

### ISSUE THREAD

**Issue by lukasrdevv** [trdwll/SteamBridge#22]
I cant build the plugin with UE 4.27.2

**Comment by trdwll** [comment]
Pull from [develop](https://github.com/trdwll/SteamBridge/tree/develop).

**Comment by trdwll** [comment]
Download [this](https://github.com/trdwll/SteamBridge/archive/refs/heads/develop.zip) and unzip it into your Plugins folder in the project.

**Comment by lukasrdevv** [comment]
Ok!

**Comment by lukasrdevv** [comment]
Ive tried it before, and there is still the same issue "scpevac could not be compiled. Try rebuilding from source manually."

**Comment by lukasrdevv** [comment]
Do you know why maybe?

**Comment by trdwll** [comment]
Jump over to the discord for better support. https://discord.gg/8EwH9twZ
