### ISSUE TITLE
OnLobbyChatUpdate CustomEvent_0  Signature Error: The function/event does not match the necessary signature - has the delegate or function/event changed?

### ISSUE THREAD

**Issue by HashemShepard** [trdwll/SteamBridge#24]
The Default Event is giving wrong signature.
![image](https://user-images.githubusercontent.com/42288517/162751429-1d54ff4f-c887-41f5-b827-122cf0dd10ae.png)

**Comment by trdwll** [comment]
Try the develop branch.

**Comment by HashemShepard** [comment]
thanks for the quick response
![image](https://user-images.githubusercontent.com/42288517/162770179-6e00487b-f633-4d1b-9039-aca62cb77248.png)
it worked but why is it an array ? which element in the array is the latest change ?

**Comment by trdwll** [comment]
No idea. It's been a long time since I worked on this.

**Comment by HashemShepard** [comment]
okay , the main issue is solved anyway 
solution : use develop branch.
