### ISSUE TITLE
"Find Leaderboard" cannot be used to "Upload Leaderboard Score" because of not matching structures

### ISSUE THREAD

**Issue by SirDiabo** [trdwll/SteamBridge#26]
Shouldn't the return value of "Find Leaderboard" be of a leaderboard struct?
To my knowledge, this makes it impossible to use the steam leaderboard :(
I checked in multiple documentations and the Find Leaderboard Function is usually supposed to be used to get that struct... please correct me if I'm wrong, though.
![1](https://user-images.githubusercontent.com/84888038/171302124-4d67faf0-5cc5-4875-9d5d-54dadffdad4a.png)
![2](https://user-images.githubusercontent.com/84888038/171302127-2085c1ca-4ec9-463a-84c1-cbc89d1d2c7b.png)
![3](https://user-images.githubusercontent.com/84888038/171302129-acc91b14-c873-436a-8bf3-12b23adfbce8.png)

**Comment by trdwll** [comment]
Forgot to respond. Yeah, no idea.

**Comment by SirDiabo** [comment]
I found out that you need to just need to call "find leaderboard" and then bind the "OnLeaderboardFindResult" to the upload function.
For some reason, find leaderboard doesn't get called, though . _.
I read through steam documentations, the code, watched how some other people set up their leaderboard and for them, it just worked. Not sure if it's a Plugin, Steam or me problem.
![image](https://user-images.githubusercontent.com/84888038/179362187-9c676d4b-de9b-4d7c-ad7d-474ada14951e.png)
![image](https://user-images.githubusercontent.com/84888038/179362200-654b022d-12cd-4ab1-ac88-a2107bee42ec.png)

**Comment by HashemShepard** [comment]
> For some reason, find leaderboard doesn't get called, though . _.
> I read through steam documentations, the code, watched how some other people set up their leaderboard and for them, it just worked. Not sure if it's a Plugin, Steam or me problem.

did you make sure that steam is actually running ? like when you open the game , it shows you the notification at the bottom , also note that steam stuff only work in standalone mode

**Comment by SirDiabo** [comment]
yup, steam is running. I tried in standalone and even after packaging. It just doesn't get called :(

**Comment by HashemShepard** [comment]
> yup, steam is running. I tried in standalone and even after packaging. It just doesn't get called :(

did you publish the changes on steamworks ?
you have to first add them here https://partner.steamgames.com/apps/achievements/1292510
and then publish the edits first 
https://partner.steamgames.com/doc/features/achievements

**Comment by trdwll** [comment]
Not sure if leaderboards work. iirc they never worked.

**Comment by Thunderdojo** [comment]
can confirm that leaderboards are not working, even tried with spacewar app id and that leaderboard, but I can not say what the exact problem is, but I do think it is not calling the event bind to leaderboards found somehow.. but not sure.
on the other hand I can confirm that achievements are working very nicely

**Comment by Thunderdojo** [comment]
Downloading/uploading leaderboard information have to be called asynchronously for whatever that means, but my give you a hint whats wrong @trdwll

**Comment by trdwll** [comment]
This stuff will be fixed soon on develop branch.
