### ISSUE TITLE
Assertion failed Errors on -game test

### ISSUE THREAD

**Issue by HashemShepard** [trdwll/SteamBridge#27]
when i started testing the game using the engine shortcut method with project directory and -game command line argument
the game crash with this error whenever i do things releated to steam
Assertion failed: IsInGameThread() || IsInSlateThread() [File:A:/UE4.26 Source/Engine/Source/Runtime/SlateCore/Private/Widgets/SWidget.cpp] [Line: "1119]" Slate can only be accessed from the GameThread or the SlateLoadingThread!
any idea why
im using ue4.26.2 source version with the plugin development branch

**Comment by trdwll** [comment]
No idea. Not sure if this is even related to SteamBridge.

**Comment by HashemShepard** [comment]
> No idea. Not sure if this is even related to SteamBridge.

well i kept googling , all i found says it has something to do with steam latent actions , and the crash only happens when interacting with steam stuff , especially lobby , like invite , join , snd msg to lobby
