### ISSUE TITLE
Steam bridge not exporting for linux

### ISSUE THREAD

**Issue by CitroenGames** [trdwll/SteamBridge#8]
PackagingResults: Error: field 'Type' is uninitialized when used here [-Werror,-Wuninitialized]
PackagingResults: Error: field 'Type' is uninitialized when used here [-Werror,-Wuninitialized]
PackagingResults: Error: field 'Type' is uninitialized when used here [-Werror,-Wuninitialized]
PackagingResults: Error: field 'Type' is uninitialized when used here [-Werror,-Wuninitialized]
PackagingResults: Error: cast to 'const char *' from smaller integer type 'char' [-Werror,-Wint-to-pointer-cast]
PackagingResults: Error: cast to 'const char *' from smaller integer type 'char' [-Werror,-Wint-to-pointer-cast]
PackagingResults: Error: field 'Type' is uninitialized when used here [-Werror,-Wuninitialized]
PackagingResults: Error: cast to 'const char *' from smaller integer type 'char' [-Werror,-Wint-to-pointer-cast]
PackagingResults: Error: field 'Type' is uninitialized when used here [-Werror,-Wuninitialized]
PackagingResults: Error: field 'Type' is uninitialized when used here [-Werror,-Wuninitialized]
PackagingResults: Error: cast to 'const char *' from smaller integer type 'char' [-Werror,-Wint-to-pointer-cast]
PackagingResults: Error: field 'Type' is uninitialized when used here [-Werror,-Wuninitialized]
PackagingResults: Error: field 'Type' is uninitialized when used here [-Werror,-Wuninitialized]
PackagingResults: Error: field 'Type' is uninitialized when used here [-Werror,-Wuninitialized]
PackagingResults: Error: field 'Type' is uninitialized when used here [-Werror,-Wuninitialized]
PackagingResults: Error: Unknown Error

this is the error i get i have exported this project does export without steambridge

**Comment by trdwll** [comment]
Should be fixed in 3b2c0d523825cc1e0e6b08fb73b0497eae093a79
